# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SavedResultsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SavedResultWindow(object):
    def setupUi(self, SavedResultWindow):
        SavedResultWindow.setObjectName("SavedResultWindow")
        SavedResultWindow.resize(960, 540)
        SavedResultWindow.setMinimumSize(QtCore.QSize(960, 540))
        SavedResultWindow.setMaximumSize(QtCore.QSize(960, 540))
        SavedResultWindow.setStyleSheet("QWidget {\n"
"       border-radius: 20px;\n"
"       background-color: #1a1328;\n"
"}")
        self.mainCard = QtWidgets.QFrame(SavedResultWindow)
        self.mainCard.setGeometry(QtCore.QRect(0, 0, 960, 540))
        self.mainCard.setMinimumSize(QtCore.QSize(960, 540))
        self.mainCard.setMaximumSize(QtCore.QSize(960, 540))
        self.mainCard.setStyleSheet("QFrame#mainCard {\n"
"    background-color: #1a1328;\n"
"    border-radius: 20px;\n"
"    border: 2px solid #26183d;\n"
"}")
        self.mainCard.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainCard.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainCard.setObjectName("mainCard")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainCard)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitle = QtWidgets.QLabel(self.mainCard)
        self.lblTitle.setMinimumSize(QtCore.QSize(100, 70))
        self.lblTitle.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(42)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitle.setFont(font)
        self.lblTitle.setStyleSheet("color: #dbd2d4;\n"
"background-color: #1a1328;\n"
"\n"
"")
        self.lblTitle.setScaledContents(False)
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout.addWidget(self.lblTitle)
        self.scrollArea = QtWidgets.QScrollArea(self.mainCard)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 942, 446))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_results = QtWidgets.QVBoxLayout()
        self.verticalLayout_results.setObjectName("verticalLayout_results")
        self.verticalLayout_3.addLayout(self.verticalLayout_results)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(SavedResultWindow)
        QtCore.QMetaObject.connectSlotsByName(SavedResultWindow)

    def retranslateUi(self, SavedResultWindow):
        _translate = QtCore.QCoreApplication.translate
        SavedResultWindow.setWindowTitle(_translate("SavedResultWindow", "Form"))
        self.lblTitle.setText(_translate("SavedResultWindow", "Saved Results"))
